project_id = "jrmvygdjsqlobpjcmhkm"

[functions.verify-password]
verify_jwt = false

[functions.change-password]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false